image: crowdar/lippia:3.2.1.1

pipelines:
  branches:
    master:  
      - step:
          name: Publish code to Github
          services:
            - docker
          trigger: automatic
          script:
            - mvn clean test -PParalelo -Dcucumber.tags=@Success
            - export PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
            - git tag $PROJECT_VERSION
            - git remote add github https://$GITHUB_USER_E:$GITHUB_TOKEN_E@github.com/Crowdar/Lippia-API-sample-project.git
            - git push -u github master
            - git push -u github $PROJECT_VERSION
            - git push origin $PROJECT_VERSION
      
